---
# vars file for pwninit
org: io12
repo: pwninit
filename: pwnint
version: latest
pwninit_config_copy_files:
  - name: pwninit-template.py
    dest: "{{ kali_user_details.home }}/.config"
pwninit_apt_dependencies:
  - elfutils
