---
# tasks list to configure firefox
- name: Firefox | configure
  block:
  - name: Firefox | Configure | Deploy ESR Policy
    become: true
    ansible.builtin.template:
      src: templates/policies.json.j2
      dest: /usr/share/firefox/distribution/policies.json
      owner: root
      group: root
      mode: 0644

  - name: Firefox | configure | Set firefox_default_profile_dir Fact
    ansible.builtin.set_fact:
      firefox_default_profile_dir: "{{ firefox_default_profile_dir_ubuntu }}"

  - name: Firefox | configure | Check If Profile Exists
    ansible.builtin.stat:
      path: "{{ firefox_default_profile_dir }}"
    register: firefox_profile

  - name: Firefox | configure | Create Default Profile
    ansible.builtin.command: "firefox -CreateProfile \"user {{ firefox_default_profile_dir }}\""
    when: not firefox_profile.stat.exists

  - name: Firefox | configure | Copy ini Files
    ansible.builtin.copy:
      src: "files/{{ item }}"
      dest: "{{ kali_user_details.home }}/.mozilla/firefox/{{ item }}"
      mode: 0600
    loop: "{{ firefox_copy_ini_files }}"

  - name: Firefox | configure | Copy user.js From quieter-firefox
    ansible.builtin.copy:
      src: files/user.js
      dest: "{{ firefox_default_profile_dir }}/user.js"
      mode: 0600
