---
namespace: borari
name: pentesting_collection
version: 1.0.6
authors:
  - borari <borari@fubared.net> (https://fubared.net)

description: An Ansible Collection to quickly stand up various pentesting systems with custom toolsets and personalized configurations.

readme: README.md
repository: https://github.com/borari/pentesting_collection
issues: https://github.com/borari/pentesting_collection/issues
documentation: https://github.com/borari/pentesting_collection
homepage: https://github.com/borari/pentesting_collection
license_file: LICENSE
license: []

dependencies:
  community.general: '>=6.2.0'
  ansible.posix: '>=1.5.0'

tags:
  - linux
  - kali
  - debian
  - system
  - hacking
  - security
  - pentesting

manifest:
  omit_default_directives: true
  directives:
    - recursive-include roles **
    - recursive-include playbooks **
    - include meta/*.yml
    - include *.txt *.md *.rst COPYING LICENSE
    - recursive-include tests **
    - recursive-include docs **.rst **.yml **.yaml **.json **.j2 **.txt
    - recursive-include roles **.yml **.yaml **.json **.j2
    - recursive-include playbooks **.yml **.yaml **.json
    - recursive-include changelogs **.yml **.yaml
    - recursive-include plugins */**.py
    - recursive-include plugins/become **.yml **.yaml
    - recursive-include plugins/cache **.yml **.yaml
    - recursive-include plugins/callback **.yml **.yaml
    - recursive-include plugins/cliconf **.yml **.yaml
    - recursive-include plugins/connection **.yml **.yaml
    - recursive-include plugins/filter **.yml **.yaml
    - recursive-include plugins/httpapi **.yml **.yaml
    - recursive-include plugins/inventory **.yml **.yaml
    - recursive-include plugins/lookup **.yml **.yaml
    - recursive-include plugins/netconf **.yml **.yaml
    - recursive-include plugins/shell **.yml **.yaml
    - recursive-include plugins/strategy **.yml **.yaml
    - recursive-include plugins/test **.yml **.yaml
    - recursive-include plugins/vars **.yml **.yaml
    - recursive-include plugins/modules **.ps1 **.yml **.yaml
    - recursive-include plugins/module_utils **.ps1 **.psm1 **.cs
    # manifest.directives from galaxy.yml inserted here
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json <namespace>-<name>-*.tar.gz
    - recursive-exclude .idea **
    - recursive-exclude .venv **
    - recursive-exclude .vscode **
    - recursive-exclude tests/output **
    - global-exclude /__pycache__
    - global-exclude pentesting_collection.iml
    - global-exclude *.tar.gz
