---
namespace: borari
name: pentesting_collection
version: 1.0.1
authors:
  - borari <borari@fubared.net> (https://fubared.net)

description: An Ansible Collection to quickly stand up various pentesting systems with custom toolsets and personalized configurations.

readme: README.md
repository: https://github.com/borari/pentesting-ansible-collection
issues: https://github.com/borari/pentesting-ansible-collection/issues
documentation: https://github.com/borari/pentesting-ansible-collection
homepage: https://github.com/borari/pentesting-ansible-collection
license_file: LICENSE
license: []

dependencies:
  community.general: '>=1.0.0'

tags:
  - linux
  - kali
  - debian
  - system
  - hacking
  - security
  - pentesting
