---
# tasks file to ensure pipx dependencies are met
- name: Pipx | Dependencies
  become: true
  when: ansible_facts['pkg_mgr'] == "apt"
  block:
  - name: Pipx | Dependencies | Install
    ansible.builtin.apt:
      name:
        - python3
        - python3-dev
        - python3-pip
        - python3-setuptools
        - pipx
      state: present
    register: apt_pip_packages
    until: apt_pip_packages is success
    retries: 1
    delay: 10
