---
# tasks list to install pipx packages
- name: Pipx | Modules | Install
  ansible.builtin.command:
    cmd: "pipx install {{ item.name }}"
    creates: "{{ item.bin }}"
  loop: "{{ pipx_packages | default([]) }}"
  when: item.name is defined
