galaxy_info:
  author: borari
  description: Installs and configures vim.
  company: fubared

  license: MIT

  min_ansible_version: '2.1'

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - system
    - security
    - pentest
    - kali
    - vim

dependencies: []
