---
# tasks list for xfce configuration
- name: Xfce | Configuration | Xfconf Settings
  community.general.xfconf:
    channel: "{{ item.channel }}"
    property: "{{ item.property }}"
    value_type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop: "{{ xfce_xconf_settings | default([]) }}"

- name: Xfce | Configuration | Ensure Dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop: "{{ xfce_ensure_dirs }}"

- name: Xfce | Configuration | Copy Settings
  ansible.builtin.copy:
    src: "files/{{ item.name }}"
    dest: "{{ item.dest }}/{{ item.name }}"
    owner: "{{ kali_user }}"
    group: "{{ kali_user }}"
    mode: 0640
    force: "{{ item.force | default(true) }}"
  loop: "{{ xfce_copy_settings }}"

- name: Xfce | Configuration | terminalrc Settings | Verify Font
  ansible.builtin.lineinfile:
    create: true
    path: "{{ kali_user_details.home }}/.config/xfce4/terminal/terminalrc"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: "{{ kali_user }}"
    group: "{{ kali_user }}"
    mode: 0664
  loop: "{{ xfce_terminalrc_settings | default([]) }}"
