galaxy_info:
  author: borari
  description: Installs firefox-esr and configures for quieter running.
  company: fubared

  license: MIT

  min_ansible_version: '2.1'

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - system
    - security
    - web
    - pentest
    - kali
    - firefox

dependencies: []
