---
# tasks file to add additonal repositories to the apt package manager
- name: Apt | add_repos
  become: true
  when: ansible_pkg_mgr == "apt"
  block:
    - name: Apt | add_repos | Add public keys
      ansible.builtin.apt_key:
        url: "{{ item.ppa_key }}"
        id: "{{ item.ppa_id }}"
        state: present
      loop: "{{ add_repos | default([]) }}"
      when: item.ppa_id is defined

    - name: Apt | Add additional repos
      ansible.builtin.apt_repository:
        repo: "{{ item.ppa }}"
        state: present
      loop: "{{ add_repos | default([]) }}"
      when: item.ppa is defined
