---
# tasks file to install apt packages
- name: Apt | Install Packages
  become: true
  when: ansible_pkg_mgr == "apt"
  block:
  - name: Apt | Update Package Lists
    ansible.builtin.apt:
      update_cache: true

  - name: Apt | Upgrade Current Packages
    ansible.builtin.apt:
      upgrade: safe

  - name: Apt | Install New Packages
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop: "{{ apt_packages | default([]) }}"
    when: item is defined
