---
# tasks file to install apt packages
- name: Apt | apt_install
  become: true
  block:
  - name: Apt | apt_install | Update Package Lists
    ansible.builtin.apt:
      update_cache: true

  - name: Apt | apt_install | Upgrade Current Packages
    ansible.builtin.apt:
      upgrade: safe

  - name: Apt | apt_install | Install New Packages
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop: "{{ apt_packages | default([]) }}"
    when: item is defined
