---
# tasks list to clean up after apt installs
- name: Apt | cleanup
  become: true
  block:
  - name: Apt | cleanup | Auto-Remove Uneccessary Packages
    ansible.builtin.apt:
      autoremove: true

  - name: Apt | cleanup | Clean Cache
    ansible.builtin.apt:
      autoclean: true
