---
# tasks file to set apt configuration settings
- name: Apt | configure
  become: true
  block:
  - name: Apt | configure | Use Kali Cloudflare Mirror
    ansible.builtin.replace:
      path: /etc/apt/sources.list
      regexp: '^(deb\s+)http://([A-Za-z0-9.-]+)(/kali.*)$'
      replace: '\1https://kali.download\3'

  - name: Apt | configure | Install Required Packages
    ansible.builtin.apt:
      name:
        - apt-transport-https
        - apt-utils
        - ca-certificates
      state: present

  - name: Apt | configure | Use HTTPS
    # Ubuntu still doesn't provide https repo mirrors. For shame!
    when: ansible_distribution != "Ubuntu"
    ansible.builtin.replace:
      path: /etc/apt/sources.list
      regexp: '^(deb\s+)http://(.*)$'
      replace: '\1https://\2'

  - name: Apt | configure | Disable systemd Timers
    ansible.builtin.systemd:
      name: "{{ item }}"
      state: stopped
      enabled: false
    loop: 
      - apt-daily.timer
      - apt-daily-upgrade.timer

  - name: Apt | configure | Disable systemd Services
    ansible.builtin.systemd:
      name: "{{ item }}"
      masked: true
    loop:
      - apt-daily.service
      - apt-daily-upgrade.service

  - name: Apt | configure | Disable Periodic Updates
    ansible.builtin.template:
      src: templates/10periodic.j2
      dest: /etc/apt/apt.conf.d/10periodic
      owner: root
      group: root
      mode: 0644

  - name: Apt | configure | Disable Languages
    ansible.builtin.lineinfile:
      create: true
      path: /etc/apt/apt.conf.d/00aptitude
      regexp: '^Acquire::Languages '
      line: 'Acquire::Languages "none";'
      owner: root
      group: root
      mode: 0644
