---
# tasks file to set apt configuration settings
- name: Apt | Configuration
  become: true
  when: ansible_pkg_mgr == "apt"
  block:
  - name: Apt | Use Kali Cloudflare Mirror
    ansible.builtin.replace:
      path: /etc/apt/sources.list
      regexp: '^(deb\s+)http://([A-Za-z0-9.-]+)(/kali.*)$'
      replace: '\1http://kali.download\3'

  - name: Apt | Install Required Packages
    ansible.builtin.apt:
      name:
        - apt-transport-https
        - apt-utils
        - ca-certificates
      state: present

  - name: Apt | Use HTTPS
    ansible.builtin.replace:
      path: /etc/apt/sources.list
      regexp: '^(deb\s+)http://(.*)$'
      replace: '\1https://\2'

  - name: Apt | Disable systemd Timers
    ansible.builtin.systemd:
      name: "{{ item }}"
      state: stopped
      enabled: false
    loop:
      - apt-daily.timer
      - apt-daily-upgrade.timer

  - name: Apt | Disable systemd Services
    ansible.builtin.systemd:
      name: "{{ item }}"
      masked: true
    loop:
      - apt-daily.service
      - apt-daily-upgrade.service

  - name: Apt | Disable Periodic Updates
    ansible.builtin.template:
      src: templates/10periodic.j2
      dest: /etc/apt/apt.conf.d/10periodic
      owner: root
      group: root
      mode: 0644
