---
# tasks file to set apt configuration settings
- name: Apt | configure
  become: true
  block:
  - name: Apt | configure | Install Required Packages
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop: "{{ apt_required_pkgs }}"

  - name: Apt | configure | Modify sources.list
    # Ubuntu still doesn't provide https repo mirrors. For shame!
    when: ansible_facts['distribution'] in ["Debian","Kali"]
    ansible.builtin.replace:
      path: /etc/apt/sources.list
      regexp: "{{ item.regexp }}"
      replace: "{{ item.replace }}"
    loop: "{{ apt_sourceslist_regex }}"

  - name: Apt | configure | Disable systemd Timers
    ansible.builtin.systemd:
      name: "{{ item }}"
      state: stopped
      enabled: false
    loop: "{{ apt_systemd_timers }}"

  - name: Apt | configure | Disable systemd Services
    ansible.builtin.systemd:
      name: "{{ item }}"
      masked: true
    loop: "{{ apt_systemd_services }}"

  - name: Apt | configure | Disable Periodic Updates
    ansible.builtin.template:
      src: templates/10periodic.j2
      dest: /etc/apt/apt.conf.d/10periodic
      owner: root
      group: root
      mode: 0644

  - name: Apt | configure | Modify 00aptitude
    ansible.builtin.lineinfile:
      create: true
      path: /etc/apt/apt.conf.d/00aptitude
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      owner: root
      group: root
      mode: 0644
    loop: "{{ apt_00aptitude_regex }}"
