---
# tasks file for apt
- name: Apt | Sanity Checks
  when: ansible_facts['pkg_mgr'] == "apt"
  block:
  - name: Apt | Import Tasks | Add Repos
    ansible.builtin.import_tasks: add_repos.yml
  - name: Apt | Import Tasks | Configure
    ansible.builtin.import_tasks: configure.yml
  - name: Apt | Import Tasks | Install | Packages
    ansible.builtin.import_tasks: apt_install.yml
  - name: Apt | Import Tasks | Cleanup
    ansible.builtin.import_tasks: cleanup.yml
