---
# tasks list to config vscode
- name: Vscode | Configuration
  block:
  - name: Vscode | Configuration | Create Dirs
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: 0750
    loop: "{{ vscode_config_dirs_linux }}"

  - name: Vscode | Configuration | Copy Files
    ansible.builtin.copy:
      src: "files/{{ item.name }}"
      dest: "{{ item.dest_dir }}/{{ item.name }}"
      mode: 0640
    loop: "{{ vscode_config_files_linux }}"
