---
# tasks file for vscode
- name: Vscode | Import Tasks | Kali
  when: ansible_facts['distribution'] in ["Kali"]
  block:
    - name: Vscode | Import Tasks | Kali | Dependencies
      ansible.builtin.include_tasks: dependencies_Kali.yml
    - name: Vscode | Import Tasks | Kali | Configuration
      ansible.builtin.include_tasks: config_Kali.yml
