---
# defaults file for xfce
xfce_required_pkgs_debian:
  - xfce4-terminal

xfce_required_pkgs_ubuntu:
  - xfce4-terminal

xfce_terminalrc_settings:
  - regexp: '^FontName='
    line: 'FontName=Hack Nerd Font Mono'
  - regexp: '^ScrollingUnlimited='
    line: 'SrollingUnlimited=TRUE'
