---
- name: IDA Free | Install | Set Installer Filename
  ansible.builtin.set_fact:
    ida_free_installer_script: idafree70_linux.run

- name: IDA Free | Install | Download Installer
  ansible.builtin.get_url:
    url: https://out7.hex-rays.com/files/{{ ida_free_installer_script }}
    dest: /tmp/{{ ida_free_installer_script }}
    mode: '0740'

- name: IDA Free | Install | Run Installer
  ansible.builtin.shell:
    cmd: /tmp/{{ ida_free_installer_script }}
    chdir: /tmp/
  changed_when: true

- name: IDA Free | Install | Clean Up
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ ida_free_cleanup_files }}"
