galaxy_info:
  author: borari
  description: Installs pipx and pipx modules.
  company: fubared

  license: MIT

  min_ansible_version: '2.1'

  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - system
    - security
    - pentest
    - kali
    - pipx

dependencies: []
