---
# vars file for kali
kali_copy_custom_scripts:
  - bumrush
  - extract

kali_configure_openssl_cnf:
  - regexp: "^MinProtocol ="
    line: "MinProtocol = None"
  - regexp: "^CipherStrings ="
    line: "CipherStrings = DEFAULT"

kali_config_create_dirs:
  - "{{ kali_user_details.home }}/.local/bin"
