---
# tasks list to configure ssh
- name: Ssh | Configuration
  become: true
  when: ansible_os_family == "Debian"
  block:
  - name: Ssh | Configuration | PermitRootLogin
    ansible.builtin.replace:
      path: /etc/ssh/sshd_config
      regexp: '(\#PermitRootLogin\s+prohibit-password)$'
      replace: 'PermitRootLogin yes'
  - name: Ssh | Configuration | Enable SSH Service
    ansible.builtin.systemd:
      name: ssh.service
      state: started
      enabled: true
