---
# tasks list to run Burp Suite env checks
- name: Burp Suite | Edition Checks
  when: 'burpsuite_product_type is undefined'
  block:
    - name: Burp Suite | Edition Prompt
      ansible.builtin.pause:
        prompt: |
          What Burp Suite product would you like to install?
            {% for p in burpsuite_products_map %}
            {{ loop.index }}. {{ p['name'] }}
            {% endfor %}

          Enter the number for the product
      register: _burpsuite_choice

    - name: Burp Suite | Set Product Type Fact
      ansible.builtin.set_fact:
        burpsuite_product_type: "{{ burpsuite_products_map[_burpsuite_choice.user_input | default(omit) | int - 1]['alias'] }}"

- name: Burp Suite | Check .burpsuitepro_licensed file
  stat:
    path: "{{ kali_user_details.home }}/.burpsuitepro_licensed"
  register: check_burpsuitepro_licensed
  when: 'burpsuite_product_type == "pro"'

- name: Burp Suite | License Checks
  when:
    - 'burpsuite_product_type == "pro"'
    - 'not check_burpsuitepro_licensed.stat.exists'
  block:
    - name: Burp Suite | License Prompt
      ansible.builtin.pause:
        prompt: "Enter the Burp Suite Pro license key:"
      register: _burpsuite_license

    - name: Burp Suite | Set License Key Fact
      ansible.builtin.set_fact:
        burpsuite_license_key: "{{ _burpsuite_license.user_input }}"

- name: Burp Suite | Save Config
  ansible.builtin.template:
    src: templates/config.yml.j2
    dest: "{{ kali_user_details.home }}/.deploy_kali_config.yml"
    mode: 0600
