---
# tasks list to install burp dependencies on debian-based distros
- name: Burp | Dependencies | Install | Apt
  become: true
  ansible.builtin.apt:
    name:
      - libfontconfig1
      - libfreetype6
      - python3-defusedxml
      - python3-pexpect
    state: present
