---
# tasks file to run dependencies for burpsuite
- name: Burp | Dependencies | Install
  block:
    - name: Burp | Dependencies | Install | Pip3
      ansible.builtin.pip:
        name: "{{ item }}"
      loop: "{{ burpsuite_required_pkgs_pip3 }}"

- name: Burp | Dependencies | Saved Settings
  block:
    - name: Burp | Dependencies | Saved Settings | Verify Edition
      ansible.builtin.stat:
        path: "{{ kali_user_details.home }}/.burpsuite_edition.yml"
      register: burp_edition_yml

    - name: Burp | Dependencies | Saved Settings | Load Edition
      ansible.builtin.include_vars: "{{ kali_user_details.home }}/.burpsuite_edition.yml"
      when: burp_edition_yml.stat.exists

    - name: Burp | Dependencies | Saved Settings | Verify License
      ansible.builtin.stat:
        path: "{{ kali_user_details.home }}/.burpsuite_license.yml"
      register: burp_license_yml

    - name: Burp | Dependencies | Saved Settings | Load License
      ansible.builtin.include_vars: "{{ kali_user_details.home }}/.burpsuite_license.yml"
      when: burp_license_yml.stat.exists
