---
- name: Burp Suite | Extras | Create Dir
  ansible.builtin.file:
    path: "{{ burpsuite_extras_dir }}"
    state: directory
    owner: "{{ burpsuite_user }}"
    group: "{{ burpsuite_user_details.group }}"
    mode: 0755

- name: Burp Suite | Extras | Download jar Files
  ansible.builtin.get_url:
    url: "{{ item.value.url }}"
    dest: "{{ burpsuite_extras_dir }}/{{ item.value.jar }}"
    checksum: "{{ item.value.checksum }}"
    owner: "{{ burpsuite_user }}"
    group: "{{ burpsuite_user_details.group }}"
    mode: '0640'
  loop: "{{ lookup('dict', burpsuite_extras_jars) }}"

- name: Burp Suite | Extras | Deploy autoburp.py
  ansible.builtin.copy:
    src: autoburp.py
    dest: "{{ burpsuite_extras_dir }}/autoburp.py"
    owner: "{{ burpsuite_user }}"
    group: "{{ burpsuite_user_details.group }}"
    mode: 0644
