---
- name: Burp Suite | Lookup Latest Version | Retrieve PortSwigger Releases API Data
  ansible.builtin.set_fact:
    burp_release_data: "{{ lookup('url', 'https://portswigger.net/burp/releases/data?lastId=-1&pageSize=20') }}"

- name: Burp Suite | Lookup Latest Version | Get Latest Release
  ansible.builtin.set_fact:
    burp_latest_release: "{{ burp_release_data | community.general.json_query(latest_release_query) }}"
  vars:
    latest_release_query: >-
      ResultSet.Results[?contains(@.releaseChannels, '{{ burpsuite_channel }}')].builds[]
      | [?ProductId == '{{ burpsuite_edition }}' && ProductPlatform == 'Linux']
      | [0]

- name: Burp Suite | Lookup Latest Version | Set Release Facts
  ansible.builtin.set_fact:
    _burpsuite_installer_version: "{{ burp_latest_release | community.general.json_query('@.Version') }}"
    burpsuite_installer_sha256_checksum: "{{ burp_latest_release | community.general.json_query('@.Sha256Checksum') }}"

- name: Burp Suite | Lookup Latest Version | Latest Version
  ansible.builtin.debug:
    msg: "Latest version for Burp Suite {{ burpsuite_edition | capitalize }} ({{ burpsuite_channel }}) is {{ _burpsuite_installer_version }}"
