---
# tasks file for burpsuite
- name: Burp | Dependencies | Check for .deploy_kali_config.yml
  ansible.builtin.stat:
    path: "{{ kali_user_details.home }}/.deploy_kali_config.yml"
  register: config_yml

- name: Burp | Dependencies | Load .deploy_kali_config.yml
  ansible.builtin.include_vars: "{{ kali_user_details.home }}/.deploy_kali_config.yml"
  when: config_yml.stat.exists

- name: Burp | Import Tasks | Env Checks
  ansible.builtin.include_tasks: burp_env_checks.yml
- name: Burp | Import Tasks | Validations
  ansible.builtin.import_tasks: validations.yml
- name: Burp | Import Tasks | Variables
  ansible.builtin.import_tasks: variables.yml

- name: Burp | Import Tasks | Lookup Latest Version
  ansible.builtin.include_tasks: lookup-latest-version.yml
  when: burpsuite_version == "latest"

# OS dependencies
- name: Burp | Import Tasks | Dependencies
  ansible.builtin.include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

# Check previous installation
- name: Burp | Import Tasks | Check Existing Installation
  ansible.builtin.import_tasks: check-previous-install.yml

# Install tasks
- name: Burp | Import Tasks | Install
  ansible.builtin.include_tasks: install.yml
  when: installed_version is not defined or installed_version != _burpsuite_installer_version

# Burp Suite extras
- name: Burp | Import Tasks | Deploy Extras
  ansible.builtin.import_tasks: deploy-extras.yml

# Activate Burp Suite
- name: Burp | Configuration | Activate and Download Public CA Cert
  ansible.builtin.command:
    cmd: "python3 autoburp.py --cacert-path '{{ burpsuite_cacert_path }}' {{ burpsuite_install_dir }}"
    chdir: "{{ burpsuite_extras_dir }}"
  environment:
    BURP_LICENSE_KEY: "{{ burpsuite_pro_license_key }}"
  async: 600
  register: autoburp
  changed_when: "'Terms and conditions accepted.' in autoburp.stdout or
    'License successfully installed and activated.' in autoburp.stdout or
    'Certificate downloaded/updated' in autoburp.stdout"
  become: true
  become_user: "{{ burpsuite_user }}"
  when: burpsuite_activate

# Create default user config
- name: Burp | Configuration | Deploy User Config
  ansible.builtin.import_tasks: user-config.yml
