---
# tasks file for burpsuite
- name: Check if .deploy_kali_config.yml exists
  ansible.builtin.stat:
    path: "{{ kali_user_details.home }}/.deploy_kali_config.yml"
  register: config_yml

- name: Load .deploy_kali_config.yml
  ansible.builtin.include_vars: "{{ kali_user_details.home }}/.deploy_kali_config.yml"
  when: config_yml.stat.exists

- ansible.builtin.include_tasks: burp_env_checks.yml
- ansible.builtin.import_tasks: validations.yml
- ansible.builtin.import_tasks: variables.yml

- name: Lookup latest version data
  ansible.builtin.include_tasks: lookup-latest-version.yml
  when: burpsuite_version == "latest"

# OS dependencies
- ansible.builtin.include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

# Check previous installation
- name: Check for previous Burp Suite installation
  ansible.builtin.import_tasks: check-previous-install.yml

# Install tasks
- name: Install Burp Suite
  ansible.builtin.include_tasks: install.yml
  when: installed_version is not defined or installed_version != _burpsuite_installer_version

# Burp Suite extras
- name: Deploy extras
  ansible.builtin.import_tasks: deploy-extras.yml

# Activate Burp Suite
- name: Activate Burp Suite and download CA public certificate
  ansible.builtin.command:
    cmd: "python3 autoburp.py --cacert-path '{{ burpsuite_cacert_path }}' {{ burpsuite_install_dir }}"
    chdir: "{{ burpsuite_extras_dir }}"
  environment:
    BURP_LICENSE_KEY: "{{ burpsuite_pro_license_key }}"
  async: 600
  register: autoburp
  changed_when: "'Terms and conditions accepted.' in autoburp.stdout or
    'License successfully installed and activated.' in autoburp.stdout or
    'Certificate downloaded/updated' in autoburp.stdout"
  become: true
  become_user: "{{ burpsuite_user }}"
  when: burpsuite_activate

# Create default user config
- name: User config
  ansible.builtin.import_tasks: user-config.yml
