---
- name: Burp Suite | User Config | Check Existing
  ansible.builtin.stat:
    path: "{{ burpsuite_user_details.home }}/.BurpSuite/UserConfig{{ burpsuite_edition | capitalize }}.json"
  register: burpsuite_user_config_stat

# Create basic user config
- name: Burp Suite | User Config | Create
  when: burpsuite_user_config_stat.stat.exists == False
  block:
    - name: Burp Suite | User Config | Create | Dir
      ansible.builtin.file:
        path: "{{ burpsuite_user_details.home }}/.BurpSuite"
        state: directory
        owner: "{{ burpsuite_user }}"
        group: "{{ burpsuite_user_details.group }}"
        mode: 0750

    - name: Burp Suite | User Config | Create | Copy Template
      ansible.builtin.template:
        src: UserConfig.json.j2
        dest: "{{ burpsuite_user_details.home }}/.BurpSuite/UserConfig{{ burpsuite_edition | capitalize }}.json"
        owner: "{{ burpsuite_user }}"
        group: "{{ burpsuite_user_details.group }}"
        mode: 0600

# Otherwise, update existing user config
- name: Burp Suite | User Config | Update 
  when: burpsuite_user_config_stat.stat.exists
  block:
    - name: Burp Suite | User Config | Update | jruby Path
      ansible.builtin.lineinfile:
        path: "{{ burpsuite_user_details.home }}/.BurpSuite/UserConfig{{ burpsuite_edition | capitalize }}.json"
        regexp: '^(.*)"location_of_jruby_jar_file":".*'
        line: '\1"location_of_jruby_jar_file":"{{ burpsuite_extras_dir }}/{{ burpsuite_extras_jars.jruby.jar }}"'
        backrefs: true

    - name: Burp Suite | User Config | Update jython Path
      ansible.builtin.lineinfile:
        path: "{{ burpsuite_user_details.home }}/.BurpSuite/UserConfig{{ burpsuite_edition | capitalize }}.json"
        regexp: '^(.*)"location_of_jython_standalone_jar_file":".*'
        line: '\1"location_of_jython_standalone_jar_file":"{{ burpsuite_extras_dir }}/{{ burpsuite_extras_jars.jython.jar }}"'
        backrefs: true
