---
# this tasks list installs the ZSH configuration files.
- name: Zsh | Configuration
  when: ansible_facts['system'] == "Linux"
  block:
  - name: Zsh | Configuration | Create Dirs
    ansible.builtin.file:
      dest: "{{ kali_user_details.home }}/{{ item }}"
      state: directory
      owner: "{{ kali_user }}"
      group: "{{ kali_user }}"
      mode: 0750
    loop:
      - .config/zsh

  - name: Zsh | Configuration | Copy Files To Home
    ansible.builtin.copy:
      src: files/.zshenv
      dest: "{{ kali_user_details.home }}/.zshenv"
      mode: 0640

  - name: Zsh | Configuration | Copy Files
    ansible.builtin.copy:
      src: "files/{{ item }}"
      dest: "{{ kali_user_details.home }}/.config/zsh/{{ item }}"
      mode: 0640
    loop:
      - .zshrc
      - .localrc
      - .zsh_paths
      - .zsh_aliases
      - .zsh_autocomp
      - .zsh_functions
      - p10k.sh
