---
# tasks list to configure metasploit
- name: Metasploit | Configuration
  become: true
  block:
  - name: Metasploit | Configuration | Enable Postgresql Service
    ansible.builtin.systemd:
      name: postgresql.service
      state: started
      enabled: true

- name: Metasploit | Configuration | Check msfdb Status
  ansible.builtin.command: msfdb status
  register: msfdb_status
  changed_when: false

- name: Metasploit | Configuration | Initialize msfdb
  ansible.builtin.command: msfdb init --component database
  when: "'No database found' in msfdb_status.stdout"
