---
# tasks list to install pspy
- name: Pspy | Install
  become: true
  when: ansible_facts['system'] == "Linux"
  block:
  - name: Pspy | Install | Create Dir
    ansible.builtin.file:
      dest: /opt/pspy
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: Pspy | Install | Download Binaries
    ansible.builtin.get_url:
      url: "https://github.com/DominicBreuker/pspy/releases/download/v1.2.1/{{ item }}"
      dest: "/opt/pspy/{{ item }}"
      owner: root
      group: root
      mode: 0755
    loop:
      - pspy64
      - pspy64s
      - pspy32
      - pspy32s
