---
# tasks file to ensure git dependencies are met
- name: Git | Dependencies
  become: true
  when: ansible_facts['pkg_mgr'] == "apt"
  block:
  - name: Git | Dependencies | Install
    ansible.builtin.apt:
      name:
        - git
      state: present
    register: apt_git_packages
    until: apt_git_packages is success
    retries: 1
    delay: 10
