---
# tasks list for cloning public git repos
- name: Git | Clone | Public
  become: true
  block:
  - name: Git | Clone | Public Repos
    ansible.builtin.git:
      repo: "{{ item.repo }}"
      dest: "{{ item.dest }}"
      version: "{{ item.version | default('master') }}"
      depth: 1
      force: true
    loop: "{{ git_repos | default([]) }}"
    when: item.dest is defined

  - name: Git | Clone | Public Repos | Update Perms
    ansible.builtin.file:
      dest: "{{ item.dest }}"
      state: directory
      mode: 0755
      owner: "{{ kali_user }}"
    loop: "{{ git_repos | default([]) }}"
    when: item.dest is defined
