---
# tasks list to configure xubuntu
- name: Xubuntu | Configuration | User
  block:
  - name: Xubuntu | Configuration | User | Create Dirs
    ansible.builtin.file:
      path: "{{ kali_user_details.home }}/{{ item }}"
      state: directory
      owner: "{{ kali_user }}"
      group: "{{ kali_user_details.group }}"
      mode: 0775
    loop: "{{ xubuntu_conf_create_dirs }}"

- name: Xubuntu | Configuration | Privileged
  become: true
  block:
    - name: Xubuntu | Configuration | Privileged | Check Services
      ansible.builtin.service_facts:

    - name: Xubuntu | Configuration | Privileged | Disable Unattended-Upgrades
      # Required because Ubuntu includes absolutely ridiculous, poorly designed defaults that include potentially locking any sofware install or even system shutdown...
      when: "'unattended-upgrades.service' in ansible_facts.services"
      block:
        - name: Xubuntu | Configuration | Privileged | Disable Unattended-Upgrades | Stop Process
          ansible.builtin.systemd:
            name: unattended-upgrades
            state: stopped

        - name: Xubuntu | Configuration | Privileged | Disable Unattended-Upgrades | Remove
          ansible.builtin.apt:
            name: unattended-upgrades
            state: absent
            purge: true
          

    - name: Xubuntu | Configuration | Privileged | Install Custom Scripts
      ansible.builtin.copy:
        src: "files/scripts/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: 0755
      loop: "{{ xubuntu_custom_scripts }}"

    - name: Xubuntu | Configuration | Privileged | Harden | systemd Services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: "{{ xubuntu_enable_systemd_svc }}"

    - name: Xubuntu | Configuration | Privileged | Harden | Set File Permissions
      ansible.builtin.file:
        path: "{{ item }}"
        mode: 0600
      loop: "{{ xubuntu_harden_file_perms }}"

    - name: Xubuntu | Configuration | Privileged | Harden | Edit Files
      ansible.builtin.lineinfile:
        create: true
        path: "{{ item.path }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        owner: root
        group: root
        mode: 0644
      loop: "{{ xubuntu_harden_lineinfiles }}"

    - name: Xubuntu | Configuration | Privileged | Harden | Deploy Templates
      ansible.builtin.template:
        src: templates/issue.net.j2
        dest: /etc/issue.net
        owner: root
        group: root
        mode: 0644

    - name: Xubuntu | Configuration | Privileged | Harden | Configure sysctl
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
      loop: "{{ xubuntu_harden_sysctl }}"
