---
# tasks list to install pip2
- name: Pip2 | Install | Debian
  become: true
  block:
  - name: Pip2 | Install | Debian | python2
    ansible.builtin.command:
      cmd: python2 /opt/pip2/get-pip.py
      creates: /usr/local/bin/pip2
