---
# vars file for ansible-role-burpsuite

_burpsuite_edition_enum:
  community: community
  pro: pro

_burpsuite_release_channel_enum:
  stable: Stable
  early_adopter: Early Adopter

burpsuite_required_pkgs_pip3:
  - jmespath

burpsuite_required_pkgs_debian:
  - libfontconfig1
  - libfreetype6
  - python3-defusedxml
  - python3-pexpect

burpsuite_required_pkgs_redhat:
  - fontconfig
  - freetype
  - python3-defusedxml
  - python3-pexpect

burpsuite_cleanup_files:
  - "/tmp/{{ burpsuite_installer_script }}"
  - /tmp/burpsuite_response.varfile
