---
# vars file for xubuntu
xubuntu_conf_create_dirs:
 - .local/bin

xubuntu_custom_scripts:
  - bumrush
  - extract

xubuntu_enable_systemd_svc:
  - apparmor.service

xubuntu_harden_file_perms:
  - /etc/crontab
  - /etc/cron.hourly
  - /etc/cron.daily
  - /etc/cron.weekly
  - /etc/cron.monthly
  - /etc/cron.d
  - /etc/ssh/ssh_config

xubuntu_harden_lineinfiles:
  - path: /etc/security/limits.conf
    regexp: '^\*        hard    core    0'
    line: '*        hard    core    0'
  - path: /etc/sysctl.conf
    regexp: '^fs\.suid_dumpable(.=.|=)'
    line: 'fs.suid_dumpable = 0'
  - path: /etc/sysctl.conf
    regexp: '^net\.ipv6\.conf\.all\.disable_ipv6(.=.|=)'
    line: 'net.ipv6.conf.all.disable_ipv6 = 1'
  - path: /etc/sysctl.conf
    regexp: '^net\.ipv6\.conf\.default\.disable_ipv6(.=.|=)'
    line: 'net.ipv6.conf.default.disable_ipv6 = 1'
  - path: /etc/ssh/sshd_config
    regexp: '^PermitEmptyPasswords '
    line: 'PermitEmptyPasswords no'
  - path: /etc/ssh/sshd_config
    regexp: '^Banner '
    line: 'Banner /etc/issue.net'
  - path: /etc/ssh/ssh_config
    regexp: '^    PermitUserEnvironment '
    line: '    PermitUserEnvironment no'
  - path: /etc/ssh/ssh_config
    regexp: '^    Banner '
    line: '    Banner /etc/issue.net'
  - path: /etc/pam.d/common-password
    regexp: '^password\t\[success=1 default=ignore\]\tpam_unix.so'
    line: 'password       [success=1 default=ignore]      pam_unix.so minlen=12 obscure yescrypt'
  - path: /etc/pam.d/common-password
    regexp: '^password\trequired\t\t\tpam_permit.so'
    line: 'password       required                        pam_permit.so retry=3 minlen=12'
  - path: /etc/login.defs
    regexp: '^PASS_MAX_DAYS'
    line: 'PASS_MAX_DAYS  30'

xubuntu_harden_sysctl:
  - name: net.ipv6.conf.all.disable_ipv6
    value: '1'
  - name: net.ipv6.conf.default.disable_ipv6
    value: '1'
