galaxy_info:
  author: borari
  description: A role to install Burp Suite, with persistent version selection and licensing.
  company: fubared

  license: MIT

  min_ansible_version: '2.1'

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - system
    - security
    - pentest
    - kali
    - burp

dependencies: []
