---
# task list to ensure vim dependencies are met
- name: Vim | Debian | Dependencies
  become: true
  block:
  - name: Vim | Debian | Dependencies | Install
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop: "{{ vim_required_pkgs_debian }}"
    register: apt_vim_packages
    until: apt_vim_packages is success
    retries: 1
    delay: 10
