---
# task list to ensure vim dependencies are met
- name: Vim | Dependencies
  become: true
  when: ansible_facts['pkg_mgr'] == "apt"
  block:
  - name: Vim | Dependencies | Install
    ansible.builtin.apt:
      name:
        - vim
        - vim-common
        - vim-runtime
        - vim-tiny
      state: present
    register: apt_vim_packages
    until: apt_vim_packages is success
    retries: 1
    delay: 10
