---
# tasks file to ensure pip3 dependencies are met
- name: Pip3 | Dependencies
  become: true
  when: ansible_facts['pkg_mgr'] == "apt"
  block:
  - name: Pip3 | Dependencies | Install
    ansible.builtin.apt:
      name:
        - python3
        - python3-dev
        - python3-pip
        - python3-setuptools
      state: present
    register: apt_pip3_packages
    until: apt_pip3_packages is success
    retries: 1
    delay: 10
