---
# tasks file for pip3
- name: Pip3 | Import Tasks | Dependencies
  ansible.builtin.include_tasks: dependencies.yml
- name: Pip3 | Import Tasks | Install
  ansible.builtin.include_tasks: pip3_install.yml
