---
# task list to ensure gdb dependencies are met
- name: Gdb | Dependencies
  become: true
  when: ansible_facts['pkg_mgr'] == "apt"
  block:
  - name: Gdb | Dependencies | Install
    ansible.builtin.apt:
      name:
        - gdb
      state: present
    register: apt_gdb_packages
    until: apt_gdb_packages is success
    retries: 1
    delay: 10
