---
# task list to ensure gdb dependencies are met
- name: Gdb | Dependencies
  become: true
  block:
  - name: Gdb | Dependencies | Debian | Install
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop: "{{ gdb_required_pkgs_debian }}"
    register: apt_gdb_packages
    until: apt_gdb_packages is success
    retries: 1
    delay: 10
  - name: Gdb | Dependencies | Debian | Create directory
    ansible.builtin.file:
      path: /opt/gef
      state: directory
  - name: Gdb | Dependencies | Debian | Clone Gef
    ansible.builtin.git:
      repo: https://github.com/hugsy/gef
      dest: /opt/gef
      single_branch: yes
      version: main
    
