---
# tasks list to config kali
- name: Kali | Config | Copy Custom Scripts
  become: true
  ansible.builtin.copy:
    src: "files/scripts/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  loop:
    - bumrush
    - extract

- name: Kali | Config | Enable AppArmor
  ansible.builtin.systemd:
    name: apparmor.service
    state: started
    enabled: true

# OpenSSL
- name: Kali | Config | Configure OpenSSL
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssl/openssl.cnf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "^MinProtocol ="
      line: "MinProtocol = None"
    - regexp: "^CipherStrings ="
      line: "CipherStrings = DEFAULT"


- name: Kali | Config | Create Dirs
  ansible.builtin.file:
    path: "{{ kali_user_details.home }}/{{ item }}"
    state: directory
    owner: "{{ kali_user }}"
    group: "{{ kali_user_details.group }}"
    mode: 0750
  loop:
    - ".local/bin"
