---
# tasks list to config kali
- name: Kali | Config | Copy Custom Scripts
  become: true
  ansible.builtin.copy:
    src: "files/scripts/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  loop: "{{ kali_copy_custom_scripts }}"

- name: Kali | Config | Enable Services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ kali_systemd_enabled_svcs }}"

# OpenSSL
- name: Kali | Config | Configure OpenSSL
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssl/openssl.cnf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: "{{ kali_configure_openssl_cnf }}"

- name: Kali | Config | Create Dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kali_user }}"
    group: "{{ kali_user_details.group }}"
    mode: 0750
  loop: "{{ kali_config_create_dirs }}"
