---
# tasks file for kali
- name: Kali | Sanity Checks
  when: ansible_facts['distribution'] != "Kali"
  block:
    - name: Kali | Sanity Checks | Failed
      ansible.builtin.debug:
        msg: "This is a {{ ansible_facts['distribution'] }} host. This is a playbook for Kali hosts. Why are you doing this?"
    - name: Kali | Sanity Check | Failed
      ansible.builtin.meta: end_host

- name: Kali | Sanity Checks
  when: ansible_facts['distribution'] in ["Kali"]
  block:
    - name: Kali | Get User Details
      user:
        name: "{{ kali_user }}"
      register: kali_user_details
    - name: Kali | Import Tasks | Configuration
      ansible.builtin.import_tasks: config.yml
