---
- name: Xubuntu Bootstrap Playbook
  hosts: '{{target|default("xubuntu")}}'  # Assumes inventory provides a 'kali' group but can also use ``-e 'target=host1,host2'``
  pre_tasks:
    - name: Xubuntu | Sanity Checks
      when: ansible_facts['distribution'] != "Ubuntu"
      block:
        - name: Xubuntu | Sanity Checks | Failed
          ansible.builtin.debug:
            msg: "This is a {{ ansible_facts['distribution'] }} host. This is a playbook for Ubuntu hosts. Why are you doing this?"

        - name: Xubuntu | Sanity Checks | Failed
          ansible.builtin.meta: end_host

  roles:
    # Run Xubuntu role for initial setup
    - xubuntu
    # Run bulk package installation roles
    - apt
#    - pip2
#    - pip3
#    - pipx
#    - ruby
#    - git
    # Run app-specific configuration roles
    - burpsuite
    - firefox
    - metasploit
    # - ossec_hids # Having issues, can't install local with ppa and build is failing. Need to implement like burpsuite role.
    - ssh
    - tmux
    - vim
    - wget
    - xfce
    - zsh
#    - pspy
#    - ysoserial
#    - gdb
#    - vscode

  post_tasks:
    - name: Xubuntu | Post-Installation Cleanup
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ kali_user_details.home }}/.zsh_history"
        - "{{ kali_user_details.home }}/.zshrc"
        - "{{ kali_user_details.home }}/.zshrc.pre-oh-my-zsh"
