---
# tasks file to ensure Ruby dependencies are met
- name: Ruby | Dependencies
  become: true
  when: ansible_facts['pkg_mgr'] == "apt"
  block:
  - name: Ruby | Dependencies | Install
    ansible.builtin.apt:
      name:
        - ruby-dev
        - ruby-rubygems
      state: present
    register: apt_rubygems_packages
    until: apt_rubygems_packages is success
    retries: 1
    delay: 10
